FROM golang:1.24 AS builder

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY . .

RUN go build -o main .

FROM debian:bookworm

WORKDIR /app

COPY --from=builder /app/main .
COPY --from=builder /app/database/migrations ./database/migrations


EXPOSE 8080

CMD [ "./main" ]
